# Generated by Django 5.2.6 on 2025-09-17 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, help_text='Текст материала (если загружается файл, поле может быть пустым)')),
                ('file', models.FileField(blank=True, null=True, upload_to='knowledge/')),
                ('tags', models.CharField(blank=True, help_text='Теги через запятую', max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('review', 'На проверке'), ('approved', 'Одобрено'), ('archived', 'Архив')], default='draft', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
