# Generated by Django 5.2.6 on 2025-09-18 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_knowledgedocument_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='document_type',
            field=models.CharField(choices=[('constitution', 'Конституция'), ('civil_code', 'Гражданский кодекс'), ('criminal_code', 'Уголовный кодекс'), ('labor_code', 'Трудовой кодекс'), ('family_code', 'Семейный кодекс'), ('administrative_code', 'Административный кодекс'), ('tax_code', 'Налоговый кодекс'), ('federal_law', 'Федеральный закон'), ('regulation', 'Постановление'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='total_chunks',
            field=models.IntegerField(default=0, verbose_name='Количество фрагментов'),
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержимое фрагмента')),
                ('chunk_index', models.IntegerField(verbose_name='Индекс фрагмента')),
                ('page_number', models.IntegerField(blank=True, null=True, verbose_name='Номер страницы')),
                ('chroma_id', models.CharField(max_length=255, unique=True, verbose_name='ID в ChromaDB')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgedocument')),
            ],
            options={
                'verbose_name': 'Фрагмент документа',
                'verbose_name_plural': 'Фрагменты документов',
                'ordering': ['document', 'chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
